# configure your datasource
quarkus:
  datasource:
    db-kind: mysql
    username: root
    password: my-secret-pw
    jdbc:
      url: jdbc:mysql://127.0.0.1:3306/social_app_db
  hibernate-orm:
    database:
      # drop and create the database at startup (use `update` to only update the schema).generation
      generation: drop-and-create
  http:
    port: 8090
